language: java

install: true

addons:
  sonarcloud:
    organization: "niels-bosman"

jdk:
  - oraclejdk11

branches:
  only:
    - main
    - develop

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar